### ISSUE TITLE
DOM shortcuts implementation

### ISSUE THREAD

**Issue by parro-it** [parro-it/electron-localshortcut#31]
I started to implement a DOM based version of `electron-localshortcut`, in an effort to make it less error prone and less "aggressive".

Many issues of this module was caused by the fact that it uses `globalShortcut` method to register shortcuts. These interferes with the other system shortcuts, often in an obstrusive way...

The new version will instead listen for `DOM` `keydown` and `keyup` events, and will trigger shortcut handlers if emitted DOM events match the registered Accelerator.

Today I published [keyboardevent-from-electron-accelerator](https://github.com/parro-it/keyboardevent-from-electron-accelerator), a module that take an Accelerator and convert it to a derived Keyboard event.

The new version of `electron-localshortcut` will use it to check if an emitted keyvoard event match a registered shortcuts.

It would be beautiful if anyone interested would check the module on [runkit](https://npm.runkit.com/keyboardevent-from-electron-accelerator) to help catch bugs before use the module as dependency here.

**Comment by ewnd9** [comment]
Related issue in `Electron` repo and suggested implementation https://github.com/electron/electron/issues/1334#issuecomment-310920998

---

> It would be beautiful if anyone interested would check the module on runkit to help catch bugs before use the module as dependency here.

I've added an issue about "super" key since I use it the most https://github.com/parro-it/keyboardevent-from-electron-accelerator/issues/5

Is there any other way to help beside manually checking everything from the regex? :sweat_smile:
